=== api-evangelist/amazon-robomaker/json-schema/amazon-robomaker-openapi-simulation-job-summary-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-robomaker/refs/heads/main/json-schema/amazon-robomaker-openapi-simulation-job-summary-schema.json",
  "title": "SimulationJobSummary",
  "description": "Summary information for a simulation job.",
  "type": "object",
  "properties": {
    "arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Arn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the simulation job."
        }
      ]
    },
    "lastUpdatedAt": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LastUpdatedAt"
        },
        {
          "description": "The time, in milliseconds since the epoch, when the simulation job was last updated."
        }
      ]
    },
    "name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Name"
        },
        {
          "description": "The name of the simulation job."
        }
      ]
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SimulationJobStatus"
        },
        {
          "description": "The status of the simulation job."
        }
      ]
    },
    "simulationApplicationNames": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SimulationApplicationNames"
        },
        {
          "description": "A list of simulation job simulation application names."
        }
      ]
    },
    "robotApplicationNames": {
      "allOf": [
        {
          "$ref": "#/components/schemas/RobotApplicationNames"
        },
        {
          "description": "A list of simulation job robot application names."
        }
      ]
    },
    "dataSourceNames": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DataSourceNames"
        },
        {
          "description": "The names of the data sources."
        }
      ]
    },
    "computeType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ComputeType"
        },
        {
          "description": "The compute type for the simulation job summary."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-robomaker/examples/amazon-robomaker-openapi-simulation-job-summary-example.json
{
  "arn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "lastUpdatedAt": "example-value",
  "name": "Example Resource",
  "status": "ACTIVE",
  "simulationApplicationNames": "Example Resource",
  "robotApplicationNames": "Example Resource",
  "dataSourceNames": "Example Resource",
  "computeType": "example-value"
}
