=== api-evangelist/amazon-robomaker/json-schema/amazon-robomaker-openapi-describe-world-generation-job-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-robomaker/refs/heads/main/json-schema/amazon-robomaker-openapi-describe-world-generation-job-response-schema.json",
  "title": "DescribeWorldGenerationJobResponse",
  "description": "DescribeWorldGenerationJobResponse schema from openapi",
  "type": "object",
  "properties": {
    "arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Arn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the world generation job."
        }
      ]
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/WorldGenerationJobStatus"
        },
        {
          "description": "<p>The status of the world generation job:</p> <dl> <dt>Pending</dt> <dd> <p>The world generation job request is pending.</p> </dd> <dt>Running</dt> <dd> <p>The world generation job is running. </p> </dd> <dt>Completed</dt> <dd> <p>The world generation job completed. </p> </dd> <dt>Failed</dt> <dd> <p>The world generation job failed. See <code>failureCode</code> for more information. </p> </dd> <dt>PartialFailed</dt> <dd> <p>Some worlds did not generate.</p> </dd> <dt>Canceled</dt> <dd> <p>The world generation job was cancelled.</p> </dd> <dt>Canceling</dt> <dd> <p>The world generation job is being cancelled.</p> </dd> </dl>"
        }
      ]
    },
    "createdAt": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CreatedAt"
        },
        {
          "description": "The time, in milliseconds since the epoch, when the world generation job was created."
        }
      ]
    },
    "failureCode": {
      "allOf": [
        {
          "$ref": "#/components/schemas/WorldGenerationJobErrorCode"
        },
        {
          "description": "<p>The failure code of the world generation job if it failed:</p> <dl> <dt>InternalServiceError</dt> <dd> <p>Internal service error.</p> </dd> <dt>LimitExceeded</dt> <dd> <p>The requested resource exceeds the maximum number allowed, or the number of concurrent stream requests exceeds the maximum number allowed. </p> </dd> <dt>ResourceNotFound</dt> <dd> <p>The specified resource could not be found. </p> </dd> <dt>RequestThrottled</dt> <dd> <p>The request was throttled.</p> </dd> <dt>InvalidInput</dt> <dd> <p>An input parameter in the request is not valid.</p> </dd> </dl>"
        }
      ]
    },
    "failureReason": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GenericString"
        },
        {
          "description": "The reason why the world generation job failed."
        }
      ]
    },
    "clientRequestToken": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ClientRequestToken"
        },
        {
          "description": "Unique, case-sensitive identifier that you provide to ensure the idempotency of the request."
        }
      ]
    },
    "template": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Arn"
        },
        {
          "description": "The Amazon Resource Name (arn) of the world template."
        }
      ]
    },
    "worldCount": {
      "allOf": [
        {
          "$ref": "#/components/schemas/WorldCount"
        },
        {
          "description": "Information about the world count."
        }
      ]
    },
    "finishedWorldsSummary": {
      "allOf": [
        {
          "$ref": "#/components/schemas/FinishedWorldsSummary"
        },
        {
          "description": "Summary information about finished worlds."
        }
      ]
    },
    "tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TagMap"
        },
        {
          "description": "A map that contains tag keys and tag values that are attached to the world generation job."
        }
      ]
    },
    "worldTags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TagMap"
        },
        {
          "description": "A map that contains tag keys and tag values that are attached to the generated worlds."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-robomaker/examples/amazon-robomaker-openapi-describe-world-generation-job-response-example.json
{
  "arn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "status": "ACTIVE",
  "createdAt": "example-value",
  "failureCode": "example-value",
  "failureReason": "example-value",
  "clientRequestToken": "example-value",
  "template": "example-value",
  "worldCount": "example-value",
  "finishedWorldsSummary": "example-value",
  "tags": "example-value"
}
