=== api-evangelist/amazon-robomaker/json-schema/amazon-robomaker-openapi-describe-world-export-job-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-robomaker/refs/heads/main/json-schema/amazon-robomaker-openapi-describe-world-export-job-response-schema.json",
  "title": "DescribeWorldExportJobResponse",
  "description": "DescribeWorldExportJobResponse schema from openapi",
  "type": "object",
  "properties": {
    "arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Arn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the world export job."
        }
      ]
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/WorldExportJobStatus"
        },
        {
          "description": "<p>The status of the world export job.</p> <dl> <dt>Pending</dt> <dd> <p>The world export job request is pending.</p> </dd> <dt>Running</dt> <dd> <p>The world export job is running. </p> </dd> <dt>Completed</dt> <dd> <p>The world export job completed. </p> </dd> <dt>Failed</dt> <dd> <p>The world export job failed. See <code>failureCode</code> and <code>failureReason</code> for more information. </p> </dd> <dt>Canceled</dt> <dd> <p>The world export job was cancelled.</p> </dd> <dt>Canceling</dt> <dd> <p>The world export job is being cancelled.</p> </dd> </dl>"
        }
      ]
    },
    "createdAt": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CreatedAt"
        },
        {
          "description": "The time, in milliseconds since the epoch, when the world export job was created."
        }
      ]
    },
    "failureCode": {
      "allOf": [
        {
          "$ref": "#/components/schemas/WorldExportJobErrorCode"
        },
        {
          "description": "<p>The failure code of the world export job if it failed:</p> <dl> <dt>InternalServiceError</dt> <dd> <p>Internal service error.</p> </dd> <dt>LimitExceeded</dt> <dd> <p>The requested resource exceeds the maximum number allowed, or the number of concurrent stream requests exceeds the maximum number allowed. </p> </dd> <dt>ResourceNotFound</dt> <dd> <p>The specified resource could not be found. </p> </dd> <dt>RequestThrottled</dt> <dd> <p>The request was throttled.</p> </dd> <dt>InvalidInput</dt> <dd> <p>An input parameter in the request is not valid.</p> </dd> </dl>"
        }
      ]
    },
    "failureReason": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GenericString"
        },
        {
          "description": "The reason why the world export job failed."
        }
      ]
    },
    "clientRequestToken": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ClientRequestToken"
        },
        {
          "description": "Unique, case-sensitive identifier that you provide to ensure the idempotency of the request."
        }
      ]
    },
    "worlds": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Arns"
        },
        {
          "description": "A list of Amazon Resource Names (arns) that correspond to worlds to be exported."
        }
      ]
    },
    "outputLocation": {
      "$ref": "#/components/schemas/OutputLocation"
    },
    "iamRole": {
      "allOf": [
        {
          "$ref": "#/components/schemas/IamRole"
        },
        {
          "description": "The IAM role that the world export process uses to access the Amazon S3 bucket and put the export."
        }
      ]
    },
    "tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TagMap"
        },
        {
          "description": "A map that contains tag keys and tag values that are attached to the world export job."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-robomaker/examples/amazon-robomaker-openapi-describe-world-export-job-response-example.json
{
  "arn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "status": "ACTIVE",
  "createdAt": "example-value",
  "failureCode": "example-value",
  "failureReason": "example-value",
  "clientRequestToken": "example-value",
  "worlds": "example-value",
  "outputLocation": "example-value",
  "iamRole": "example-value",
  "tags": "example-value"
}
